name: Build

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (you can adjust the branches)

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clones to ensure full history is available for analysis

      # Step 2: Set up Java (only if needed for Java-based projects)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Modify if you're using a different version or no Java

      # Step 3: Install SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          sudo apt-get install unzip
          sudo unzip /tmp/sonar-scanner.zip -d /opt/
          sudo ln -s /opt/sonar-scanner-*/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # Step 4: Run SonarScanner with -X for debug logging
      - name: Run SonarScanner with debug logging
        run: |
          sonar-scanner -X \
            -Dsonar.projectKey=my-node-app  # Replace with your actual project key
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.verbose=true  # Enable verbose logs
