    - name: Run SonarScanner with debug logging
      run: |
        sonar-scanner -X \
          -Dsonar.projectKey=my-node-app \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
