name: Build

on:
  push:
    branches:
      - main  # You can change this if you want to trigger the scan on other branches

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest  # You can change this to another OS if needed

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clones to ensure full history is available for analysis

      # Step 2: Run SonarQube scan with debug logging
      - name: Run SonarQube scan with debug logging
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          sonar-project-key: my-node-app  # Replace with your project key
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-login: ${{ secrets.SONAR_TOKEN }}
          sonar.verbose: true  # Enable debug logging for SonarQube scanner

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Set secret for the token (authentication)
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Set SonarQube server URL
